format:
  html: {toc: true, toc-depth: 4, theme: spacelab}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Linear Regression
  chapters: [index.qmd, assignment.eda.qmd, assignment.scicloj.qmd, assignment.sklearn.qmd, assignment.conclusion.qmd]
